---
-
  name: install apache 
  hosts: web01.labs.corp
  user: root
  #sudo: true
  vars:



  tasks:

     - name: server is running 
       ping:
         data: pong 
    
     - name: install apache 
       yum: 
         name: httpd 
         state: latest 

     - name: enable service 
       service: 
           name: httpd 
           state: started 

     - name: release port in firewall 
       firewalld: 
            port: 80/tcp 
            permanent: yes 
            state: enabled
            immediate: yes 
            
